sudo: false

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

